In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data.csv')

In [3]:
data

,client_id,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,...,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type
0,fe60b594364f9f636266ed1ef4f89c32,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Platinum Rewards,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc
1,3012cabca5885ed53d348d6e57dab5de,М,1951,2009-09-24,R,0,Ишимбай,NaN,0.0,Договор на текущий счет для дебетовой карты,...,VISA Classic,2019.0,NaN,0.0,0,1900.0,1000.0,6200.0,3000.0,dc
2,d871ef96820b6c7a1ada8e01a772724e,Ж,1982,2006-12-25,R,0,Юрга,NaN,0.0,Договор на текущий счет для дебетовой карты,...,NaN,NaN,NaN,0.0,0,0.0,0.0,0.0,0.0,dc
3,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Visa Rewards,2021.0,NaN,24300.0,118,0.0,0.0,35400.0,35400.0,cc
4,0bacbc2abd314f9fac031d249e485a7b,М,1955,2011-04-15,R,0,Томск,NaN,0.0,Договор на текущий счет для дебетовой карты,...,Eurocard/MasterCard World,2018.0,2022.0,24300.0,118,0.0,0.0,35400.0,35400.0,cc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371578,d69d3201104ab393c0638839a7284ad7,М,1953,2018-08-08,R,0,Пятигорск,NaN,200000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,300.0,9900.0,10100.0,dc
371579,a936fb30e2268d2874cdcaa221032915,М,1997,2022-05-12,R,0,Кемерово,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,15000.0,33,0.0,0.0,15000.0,15000.0,dc
371580,a9cf0bb4f06fa321704ced777e993b33,М,1983,2021-10-15,R,0,Санкт-Петербург,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,600.0,5,0.0,0.0,1100.0,1100.0,dc
371581,f69eb17242ca85eb21349dc08220afb8,Ж,1986,2022-02-12,R,0,Уфа,NaN,15000.0,Кредитная карта,...,NaN,NaN,NaN,0.0,0,0.0,0.0,1100.0,1100.0,dc
371582,93237191eddf8dec77cc947c3c086358,Ж,1959,2012-07-19,R,0,Москва,NaN,30000.0,Кредитная карта,...,NaN,NaN,NaN,9900.0,19,0.0,0.0,29900.0,29900.0,dc

In [3]:
new_data = data.copy().drop(['client_id', 'card_id'], axis=1)

In [4]:
new_data['client_age'] = 2022 - new_data['birth_date']

In [5]:
new_data['client_age'].mean()

43.594631616624014

In [6]:
pd.merge(new_data[new_data['current_balance_avg_sum'] != 0], new_data[new_data['purchase_count'] != 0], how='inner')

,gender,birth_date,create_date,nonresident_flag,businessman_flag,city,term,contract_sum,product_category_name,card_type_name,start_date,fact_close_date,purchase_sum,purchase_count,current_balance_avg_sum,current_balance_sum,current_debit_turn_sum,current_credit_turn_sum,card_type,client_age
0,Ж,1985,2020-01-29,R,0,Гусь-Хрустальный,NaN,0.0,Договор на текущий счет для дебетовой карты,Visa Platinum Rewards,2019.0,2021.0,16600.0,71,39700.0,25700.0,220600.0,201000.0,dc,37
1,М,1989,2010-12-16,R,0,Туапсе,NaN,0.0,Договор на текущий счет для дебетовой карты,Eurocard/MasterCard Mass,2019.0,NaN,9700.0,33,6100.0,10200.0,13800.0,23500.0,dc,33
2,М,1989,2010-12-16,R,0,Туапсе,NaN,0.0,Договор на текущий счет для дебетовой карты,Eurocard/MasterCard Mass,2021.0,NaN,9700.0,33,6100.0,10200.0,13800.0,23500.0,dc,33
3,М,1989,2010-12-16,R,0,Туапсе,NaN,0.0,Договор на текущий счет для дебетовой карты,Eurocard/MasterCard Mass,2018.0,2019.0,9700.0,33,6100.0,10200.0,13800.0,23500.0,dc,33
4,Ж,1979,2005-05-18,R,0,Уфа,NaN,0.0,Договор на текущий счет для дебетовой карты,Visa Platinum Rewards,2020.0,NaN,10000.0,26,20800.0,26000.0,10000.0,36000.0,dc,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130257,Ж,1962,2019-04-30,R,0,Курганинск,NaN,6000.0,Договор на текущий счет для дебетовой карты,МИР Debit,2022.0,NaN,6100.0,9,1100.0,1200.0,9300.0,3000.0,dc,60
130258,Ж,1990,2021-06-22,R,0,Краснодар,NaN,0.0,Договор на текущий счет для дебетовой карты,"Дебет карта ПС МИР ""Бюджетная""",2021.0,NaN,5500.0,71,56800.0,54600.0,23700.0,27400.0,dc,32
130259,М,1990,2022-02-03,N,0,Москва,NaN,0.0,Договор на текущий счет для дебетовой карты,Eurocard/MasterCard Mass,2022.0,NaN,500.0,3,1500.0,6700.0,12400.0,12200.0,dc,32
130260,М,1976,2014-06-16,R,0,Екатеринбург,NaN,0.0,Договор на текущий счет для дебетовой карты,Visa Platinum Rewards,2021.0,NaN,1000.0,4,100.0,0.0,30000.0,30000.0,dc,46
130261,М,1977,2007-05-21,R,0,Ейск,NaN,500000.0,Кредитная карта,NaN,NaN,NaN,179800.0,8,100.0,0.0,240100.0,239800.0,dc,45

In [8]:
(371583 - 210431) / 371583

0.43369045408428264

In [20]:
cities = new_data['city'].value_counts().to_dict()
cities

{'Уфа': 59076,
 'Москва': 31072,
 'Краснодар': 21470,
 'Санкт-Петербург': 12982,
 'Стерлитамак': 12454,
 'Салават': 6952,
 'Туймазы': 6253,
 'Омск': 5898,
 'Октябрьский': 5646,
 'Новосибирск': 5641,
 'Смоленск': 5366,
 'Екатеринбург': 5324,
 'Брянск': 5314,
 'Нефтекамск': 5263,
 'Учалы': 5235,
 'Ишимбай': 5007,
 'Челябинск': 4303,
 'Белорецк': 3869,
 'Сибай': 3789,
 'Бирск': 3580,
 'Туапсе': 3560,
 'Пермь': 3558,
 'Сочи': 3532,
 'Белебей': 3517,
 'Кемерово': 3328,
 'Кунгур': 3179,
 'Владимир': 3145,
 'Кумертау': 3114,
 'Анапа': 2981,
 'Месягутово': 2963,
 'Тюмень': 2920,
 'Ростов-на-Дону': 2839,
 'Армавир': 2822,
 'Янаул': 2790,
 'Нижний Новгород': 2615,
 'Ейск': 2610,
 'Мелеуз': 2389,
 'Чишмы': 2344,
 'Златоуст': 2331,
 'Дюртюли': 2310,
 'Юрга': 2175,
 'Благовещенск': 2049,
 'Ижевск': 2047,
 'Осинники': 2022,
 'Клинцы': 1954,
 'Новокузнецк': 1941,
 'Новороссийск': 1939,
 'Вологда': 1858,
 'Геленджик': 1850,
 'Саратов': 1778,
 'Баймак': 1766,
 'Раевский': 1737,
 'Магнитогорск': 1692,
 'Набережные Челны': 1528,
 'Толбазы': 1526,
 'Рязань': 1522,
 'Великий Новгород': 1506,
 'Жуковский': 1446,
 'Нижневартовск': 1438,
 'Давлеканово': 1435,
 'Калининград': 1337,
 'Орёл': 1325,
 'Сургут': 1274,
 'Иглино': 1256,
 'Воронеж': 1211,
 'Серпухов': 1205,
 'Томск': 1189,
 'Таганрог': 1189,
 'Волгоград': 1187,
 'Петрозаводск': 1171,
 'Кропоткин': 1135,
 'Кореновск': 1090,
 'Ставрополь': 1061,
 'Химки': 1035,
 'Прокопьевск': 1024,
 'Старосубхангулово': 1011,
 'Красноярск': 1003,
 'Ковров': 1001,
 'Гусь-Хрустальный': 991,
 'Тамбов': 965,
 'Дзержинск': 962,
 'Тверь': 959,
 'Иркутск': 942,
 'Воскресенск': 937,
 'Стерлибашево': 936,
 'Белгород': 931,
 'Невинномысск': 928,
 'Сергиев Посад': 924,
 'Караидель': 913,
 'Тимашевск': 908,
 'Покров': 906,
 'Красноусольский': 892,
 'Бийск': 874,
 'Киселёвск': 872,
 'Миасс': 820,
 'Одинцово': 804,
 'Старобалтачево': 784,
 'Казань': 773,
 'Тула': 767,
 'Раменское': 728,
 'Пенза': 724,
 'Курган': 718,
 'Дубна': 706,
 'Федоровка': 706,
 'Аскарово': 684,
 'Верхнеяркеево': 679,
 'Калтан': 676,
 'Архангельск': 645,
 'Белово': 643,
 'Самара': 621,
 'Старый Оскол': 600,
 'Мраково': 585,
 'Рославль': 577,
 'Калтасы': 552,
 'Верхние Татышлы': 542,
 'Муром': 531,
 'Барнаул': 528,
 'Надым': 527,
 'Зилаир': 520,
 'Сарапул': 517,
 'Колпино': 507,
 'Боровичи': 499,
 'Серафимовский': 491,
 'Аскино': 490,
 'Киргиз-Мияки': 480,
 'Агидель': 394,
 'Чусовой': 391,
 'Липецк': 374,
 'Архангельское': 370,
 'Кандры': 345,
 'Бураево': 343,
 'Мегион': 333,
 'Ульяновск': 325,
 'Междуреченск': 317,
 'Приютово': 316,
 'Светлый': 311,
 'Каневская': 296,
 'Пятигорск': 292,
 'Вольск': 285,
 'Череповец': 261,
 'Янгантау': 247,
 'Глазов': 245,
 'Воткинск': 217,
 'Ярославль': 213,
 'Исянгулово': 201,
 'Березники': 200,
 'Курганинск': 197,
 'Ангарск': 191,
 'Языково': 131,
 'Николо-Березовка': 102}

In [7]:
registrations = new_data['create_date'].value_counts().sort_index(ascending=False).to_dict()

In [8]:
registrations

{'2022-05-25': 2,
 '2022-05-24': 2,
 '2022-05-23': 4,
 '2022-05-22': 2,
 '2022-05-21': 6,
 '2022-05-20': 2,
 '2022-05-19': 6,
 '2022-05-18': 1,
 '2022-05-17': 8,
 '2022-05-15': 4,
 '2022-05-14': 5,
 '2022-05-13': 3,
 '2022-05-12': 20,
 '2022-05-11': 1,
 '2022-05-08': 2,
 '2022-05-07': 2,
 '2022-05-06': 6,
 '2022-05-05': 3,
 '2022-05-03': 6,
 '2022-05-01': 4,
 '2022-04-30': 7,
 '2022-04-29': 3,
 '2022-04-28': 7,
 '2022-04-27': 13,
 '2022-04-26': 16,
 '2022-04-25': 24,
 '2022-04-24': 2,
 '2022-04-22': 28,
 '2022-04-21': 22,
 '2022-04-20': 40,
 '2022-04-19': 14,
 '2022-04-18': 25,
 '2022-04-16': 6,
 '2022-04-15': 29,
 '2022-04-14': 40,
 '2022-04-13': 20,
 '2022-04-12': 6,
 '2022-04-11': 15,
 '2022-04-10': 15,
 '2022-04-09': 4,
 '2022-04-08': 26,
 '2022-04-07': 12,
 '2022-04-06': 14,
 '2022-04-05': 12,
 '2022-04-04': 16,
 '2022-04-03': 14,
 '2022-04-02': 4,
 '2022-04-01': 14,
 '2022-03-31': 12,
 '2022-03-30': 7,
 '2022-03-29': 5,
 '2022-03-28': 57,
 '2022-03-26': 6,
 '2022-03-25': 7,
 '2022-03-24': 17,
 '2022-03-23': 15,
 '2022-03-22': 12,
 '2022-03-21': 18,
 '2022-03-20': 3,
 '2022-03-19': 8,
 '2022-03-18': 25,
 '2022-03-17': 48,
 '2022-03-16': 34,
 '2022-03-15': 24,
 '2022-03-14': 28,
 '2022-03-13': 9,
 '2022-03-12': 6,
 '2022-03-11': 99,
 '2022-03-10': 33,
 '2022-03-09': 49,
 '2022-03-08': 3,
 '2022-03-06': 9,
 '2022-03-05': 15,
 '2022-03-04': 44,
 '2022-03-03': 69,
 '2022-03-02': 26,
 '2022-03-01': 71,
 '2022-02-28': 16,
 '2022-02-25': 31,
 '2022-02-24': 28,
 '2022-02-23': 12,
 '2022-02-22': 31,
 '2022-02-21': 69,
 '2022-02-20': 6,
 '2022-02-19': 3,
 '2022-02-18': 19,
 '2022-02-17': 26,
 '2022-02-16': 69,
 '2022-02-15': 18,
 '2022-02-14': 50,
 '2022-02-12': 32,
 '2022-02-11': 30,
 '2022-02-10': 5,
 '2022-02-09': 12,
 '2022-02-08': 19,
 '2022-02-07': 23,
 '2022-02-04': 32,
 '2022-02-03': 36,
 '2022-02-02': 28,
 '2022-02-01': 20,
 '2022-01-31': 29,
 '2022-01-30': 5,
 '2022-01-29': 8,
 '2022-01-28': 63,
 '2022-01-27': 24,
 '2022-01-26': 49,
 '2022-01-25': 19,
 '2022-01-24': 34,
 '2022-01-23': 8,
 '2022-01-22': 8,
 '2022-01-21': 15,
 '2022-01-20': 5,
 '2022-01-19': 10,
 '2022-01-18': 18,
 '2022-01-17': 34,
 '2022-01-16': 8,
 '2022-01-14': 10,
 '2022-01-13': 49,
 '2022-01-12': 40,
 '2022-01-11': 20,
 '2021-12-30': 34,
 '2021-12-29': 32,
 '2021-12-28': 21,
 '2021-12-27': 59,
 '2021-12-26': 6,
 '2021-12-24': 12,
 '2021-12-23': 42,
 '2021-12-22': 73,
 '2021-12-21': 24,
 '2021-12-20': 24,
 '2021-12-19': 10,
 '2021-12-18': 6,
 '2021-12-17': 66,
 '2021-12-16': 28,
 '2021-12-15': 76,
 '2021-12-14': 29,
 '2021-12-13': 34,
 '2021-12-12': 12,
 '2021-12-11': 12,
 '2021-12-10': 72,
 '2021-12-09': 30,
 '2021-12-08': 59,
 '2021-12-07': 46,
 '2021-12-06': 11,
 '2021-12-03': 60,
 '2021-12-02': 103,
 '2021-12-01': 104,
 '2021-11-30': 55,
 '2021-11-29': 50,
 '2021-11-28': 6,
 '2021-11-26': 90,
 '2021-11-25': 91,
 '2021-11-24': 154,
 '2021-11-23': 28,
 '2021-11-22': 56,
 '2021-11-19': 37,
 '2021-11-18': 49,
 '2021-11-17': 53,
 '2021-11-16': 67,
 '2021-11-15': 75,
 '2021-11-14': 21,
 '2021-11-13': 7,
 '2021-11-12': 28,
 '2021-11-11': 68,
 '2021-11-10': 119,
 '2021-11-09': 50,
 '2021-11-08': 49,
 '2021-11-07': 7,
 '2021-11-04': 37,
 '2021-11-03': 48,
 '2021-11-02': 97,
 '2021-11-01': 49,
 '2021-10-30': 7,
 '2021-10-29': 163,
 '2021-10-28': 29,
 '2021-10-27': 38,
 '2021-10-26': 65,
 '2021-10-25': 40,
 '2021-10-22': 33,
 '2021-10-21': 31,
 '2021-10-20': 108,
 '2021-10-19': 67,
 '2021-10-18': 16,
 '2021-10-17': 21,
 '2021-10-16': 22,
 '2021-10-15': 65,
 '2021-10-14': 24,
 '2021-10-13': 55,
 '2021-10-12': 54,
 '2021-10-08': 64,
 '2021-10-07': 24,
 '2021-10-06': 52,
 '2021-10-05': 82,
 '2021-10-04': 66,
 '2021-10-02': 21,
 '2021-10-01': 109,
 '2021-09-30': 52,
 '2021-09-29': 60,
 '2021-09-28': 17,
 '2021-09-27': 127,
 '2021-09-26': 10,
 '2021-09-24': 157,
 '2021-09-23': 101,
 '2021-09-22': 123,
 '2021-09-21': 286,
 '2021-09-20': 140,
 '2021-09-17': 75,
 '2021-09-16': 165,
 '2021-09-15': 139,
 '2021-09-14': 104,
 '2021-09-13': 277,
 '2021-09-12': 9,
 '2021-09-11': 17,
 '2021-09-10': 158,
 '2021-09-09': 212,
 '2021-09-08': 43,
 '2021-09-07': 104,
 '2021-09-06': 63,
 '2021-09-03': 108,
 '2021-09-02': 106,
 '2021-09-01': 71,
 '2021-08-31': 37,
 '2021-08-30': 109,
 '2021-08-29': 6,
 '2021-08-27': 169,
 '2021-08-26': 69,
 '2021-08-25': 120,
 '2021-08-24': 190,
 '2021-08-23': 93,
 '2021-08-20': 85,
 '2021-08-19': 76,
 '2021-08-18': 50,
 '2021-08-17': 68,
 '2021-08-16': 28,
 '2021-08-13': 33,
 '2021-08-12': 59,
 '2021-08-11': 50,
 '2021-08-10': 138,
 '2021-08-09': 52,
 '2021-08-08': 10,
 '2021-08-07': 6,
 '2021-08-06': 10,
 '2021-08-05': 47,
 '2021-08-04': 38,
 '2021-08-03': 80,
 '2021-08-02': 80,
 '2021-07-31': 10,
 '2021-07-30': 51,
 '2021-07-29': 111,
 '2021-07-28': 139,
 '2021-07-27': 116,
 '2021-07-26': 115,
 '2021-07-23': 30,
 '2021-07-22': 44,
 '2021-07-21': 77,
 '2021-07-20': 87,
 '2021-07-19': 127,
 '2021-07-17': 11,
 '2021-07-16': 100,
 '2021-07-15': 180,
 '2021-07-14': 66,
 '2021-07-13': 103,
 '2021-07-12': 43,
 '2021-07-11': 10,
 '2021-07-09': 85,
 '2021-07-08': 55,
 '2021-07-07': 85,
 '2021-07-06': 103,
 '2021-07-05': 11,
 '2021-07-02': 101,
 '2021-07-01': 97,
 '2021-06-30': 12,
 '2021-06-29': 96,
 '2021-06-28': 59,
 '2021-06-26': 12,
 '2021-06-25': 35,
 '2021-06-24': 24,
 '2021-06-23': 45,
 '2021-06-22': 81,
 '2021-06-21': 39,
 '2021-06-20': 39,
 '2021-06-19': 9,
 '2021-06-18': 47,
 '2021-06-17': 60,
 '2021-06-16': 174,
 '2021-06-15': 172,
 '2021-06-11': 44,
 '2021-06-10': 103,
 '2021-06-09': 117,
 '2021-06-08': 60,
 '2021-06-07': 60,
 '2021-06-04': 133,
 '2021-06-03': 67,
 '2021-06-02': 154,
 '2021-06-01': 36,
 '2021-05-31': 53,
 '2021-05-29': 42,
 '2021-05-28': 26,
 '2021-05-27': 38,
 '2021-05-26': 52,
 '2021-05-25': 56,
 '2021-05-24': 13,
 '2021-05-21': 227,
 '2021-05-20': 133,
 '2021-05-19': 128,
 '2021-05-18': 250,
 '2021-05-17': 97,
 '2021-05-14': 108,
 '2021-05-13': 130,
 '2021-05-12': 168,
 '2021-05-11': 179,
 '2021-05-07': 90,
 '2021-05-06': 26,
 '2021-05-05': 42,
 '2021-05-04': 83,
 '2021-05-01': 21,
 '2021-04-30': 156,
 '2021-04-29': 72,
 '2021-04-28': 113,
 '2021-04-27': 82,
 '2021-04-26': 42,
 '2021-04-24': 12,
 '2021-04-23': 144,
 '2021-04-22': 65,
 '2021-04-21': 96,
 '2021-04-20': 72,
 '2021-04-19': 161,
 '2021-04-17': 14,
 '2021-04-16': 156,
 '2021-04-15': 63,
 '2021-04-14': 290,
 '2021-04-13': 121,
 '2021-04-12': 54,
 '2021-04-09': 126,
 '2021-04-08': 83,
 '2021-04-07': 114,
 '2021-04-06': 103,
 '2021-04-05': 70,
 '2021-04-03': 31,
 '2021-04-02': 52,
 '2021-04-01': 77,
 '2021-03-31': 69,
 '2021-03-30': 132,
 '2021-03-29': 56,
 '2021-03-27': 15,
 '2021-03-26': 119,
 '2021-03-25': 169,
 '2021-03-24': 178,
 '2021-03-23': 161,
 '2021-03-22': 118,
 '2021-03-20': 21,
 '2021-03-19': 114,
 '2021-03-18': 90,
 '2021-03-17': 88,
 '2021-03-16': 91,
 '2021-03-15': 133,
 '2021-03-12': 148,
 '2021-03-11': 135,
 '2021-03-10': 283,
 '2021-03-09': 88,
 '2021-03-05': 45,
 '2021-03-04': 99,
 '2021-03-03': 15,
 '2021-03-02': 120,
 '2021-03-01': 120,
 '2021-02-26': 69,
 '2021-02-25': 139,
 '2021-02-24': 48,
 '2021-02-22': 18,
 '2021-02-20': 47,
 '2021-02-19': 211,
 '2021-02-18': 126,
 '2021-02-17': 122,
 '2021-02-16': 229,
 '2021-02-15': 56,
 '2021-02-13': 16,
 '2021-02-12': 129,
 '2021-02-11': 128,
 '2021-02-10': 93,
 '2021-02-09': 138,
 '2021-02-08': 104,
 '2021-02-05': 87,
 '2021-02-04': 127,
 '2021-02-03': 169,
 '2021-02-02': 187,
 '2021-02-01': 177,
 '2021-01-29': 186,
 '2021-01-28': 109,
 '2021-01-27': 85,
 '2021-01-26': 159,
 '2021-01-25': 224,
 '2021-01-23': 30,
 '2021-01-22': 34,
 '2021-01-21': 83,
 '2021-01-20': 83,
 '2021-01-19': 227,
 '2021-01-18': 83,
 '2021-01-17': 23,
 '2021-01-16': 43,
 '2021-01-15': 54,
 '2021-01-14': 49,
 '2021-01-13': 34,
 '2021-01-12': 173,
 '2021-01-11': 119,
 '2021-01-09': 17,
 '2021-01-06': 17,
 '2020-12-31': 18,
 '2020-12-30': 36,
 '2020-12-29': 35,
 '2020-12-28': 69,
 '2020-12-26': 18,
 '2020-12-25': 18,
 '2020-12-24': 216,
 '2020-12-23': 128,
 '2020-12-22': 270,
 '2020-12-21': 163,
 '2020-12-18': 340,
 '2020-12-17': 74,
 '2020-12-16': 108,
 '2020-12-15': 141,
 '2020-12-14': 221,
 '2020-12-11': 179,
 '2020-12-10': 290,
 '2020-12-09': 205,
 '2020-12-08': 86,
 '2020-12-07': 125,
 '2020-12-05': 18,
 '2020-12-04': 18,
 '2020-12-03': 168,
 '2020-12-02': 203,
 '2020-12-01': 163,
 '2020-11-30': 111,
 '2020-11-27': 299,
 '2020-11-26': 154,
 '2020-11-25': 202,
 '2020-11-24': 109,
 '2020-11-23': 105,
 '2020-11-20': 156,
 '2020-11-19': 261,
 '2020-11-18': 204,
 '2020-11-17': 74,
 '2020-11-16': 177,
 '2020-11-13': 230,
 '2020-11-12': 56,
 '2020-11-11': 202,
 '2020-11-10': 127,
 '2020-11-09': 134,
 '2020-11-08': 19,
 '2020-11-06': 188,
 '2020-11-05': 75,
 '2020-11-03': 139,
 '2020-11-02': 71,
 '2020-11-01': 55,
 '2020-10-30': 289,
 '2020-10-29': 232,
 '2020-10-28': 146,
 '2020-10-27': 58,
 '2020-10-26': 60,
 '2020-10-25': 64,
 '2020-10-23': 139,
 '2020-10-22': 47,
 '2020-10-21': 105,
 '2020-10-20': 57,
 '2020-10-19': 136,
 '2020-10-17': 20,
 '2020-10-16': 153,
 '2020-10-15': 191,
 '2020-10-14': 240,
 '2020-10-13': 233,
 '2020-10-12': 58,
 '2020-10-11': 20,
 '2020-10-10': 20,
 '2020-10-09': 24,
 '2020-10-08': 244,
 '2020-10-07': 349,
 '2020-10-06': 490,
 '2020-10-05': 143,
 '2020-10-02': 314,
 '2020-10-01': 202,
 '2020-09-30': 143,
 '2020-09-29': 181,
 '2020-09-28': 206,
 '2020-09-26': 21,
 '2020-09-25': 151,
 '2020-09-24': 215,
 '2020-09-23': 229,
 '2020-09-22': 260,
 '2020-09-21': 465,
 '2020-09-19': 63,
 '2020-09-18': 322,
 '2020-09-17': 313,
 '2020-09-16': 617,
 '2020-09-15': 587,
 '2020-09-14': 467,
 '2020-09-11': 412,
 '2020-09-10': 515,
 '2020-09-09': 419,
 '2020-09-08': 528,
 '2020-09-07': 526,
 '2020-09-06': 41,
 '2020-09-05': 62,
 '2020-09-04': 215,
 '2020-09-03': 510,
 '2020-09-02': 117,
 '2020-09-01': 287,
 '2020-08-31': 157,
 '2020-08-28': 278,
 '2020-08-27': 235,
 '2020-08-26': 129,
 '2020-08-25': 129,
 '2020-08-24': 257,
 '2020-08-21': 73,
 '2020-08-20': 134,
 '2020-08-19': 22,
 '2020-08-18': 152,
 '2020-08-17': 112,
 '2020-08-14': 66,
 '2020-08-13': 60,
 '2020-08-12': 55,
 '2020-08-11': 121,
 '2020-08-10': 82,
 '2020-08-07': 299,
 '2020-08-06': 66,
 '2020-08-05': 66,
 '2020-08-04': 72,
 '2020-08-03': 88,
 '2020-08-01': 150,
 '2020-07-31': 238,
 '2020-07-30': 260,
 '2020-07-29': 115,
 '2020-07-28': 26,
 '2020-07-27': 23,
 '2020-07-25': 23,
 '2020-07-24': 69,
 '2020-07-23': 520,
 '2020-07-22': 111,
 '2020-07-21': 78,
 '2020-07-20': 46,
 '2020-07-18': 13,
 '2020-07-17': 278,
 '2020-07-16': 155,
 '2020-07-15': 87,
 '2020-07-14': 175,
 '2020-07-13': 117,
 '2020-07-10': 99,
 '2020-07-09': 50,
 '2020-07-08': 115,
 '2020-07-07': 180,
 '2020-07-06': 46,
 '2020-07-03': 90,
 '2020-07-02': 179,
 '2020-06-30': 166,
 '2020-06-29': 138,
 '2020-06-26': 141,
 '2020-06-25': 185,
 '2020-06-23': 189,
 '2020-06-22': 87,
 '2020-06-19': 133,
 '2020-06-18': 210,
 '2020-06-17': 389,
 '2020-06-16': 181,
 '2020-06-15': 79,
 '2020-06-14': 38,
 '2020-06-11': 93,
 '2020-06-10': 95,
 '2020-06-09': 127,
 '2020-06-08': 48,
 '2020-06-07': 23,
 '2020-06-05': 96,
 '2020-06-04': 248,
 '2020-06-03': 61,
 '2020-06-02': 158,
 '2020-06-01': 74,
 '2020-05-30': 24,
 '2020-05-29': 86,
 '2020-05-28': 69,
 '2020-05-27': 53,
 '2020-05-26': 140,
 '2020-05-25': 275,
 '2020-05-22': 94,
 '2020-05-21': 118,
 '2020-05-20': 192,
 '2020-05-19': 72,
 '2020-05-18': 188,
 '2020-05-16': 38,
 '2020-05-15': 341,
 '2020-05-14': 48,
 '2020-05-13': 137,
 '2020-05-12': 83,
 '2020-05-10': 7,
 '2020-05-08': 72,
 '2020-05-07': 84,
 '2020-05-06': 120,
 '2020-05-01': 7,
 '2020-04-30': 226,
 '2020-04-29': 49,
 '2020-04-27': 197,
 '2020-04-26': 6,
 '2020-04-24': 119,
 '2020-04-23': 120,
 '2020-04-22': 161,
 '2020-04-21': 140,
 '2020-04-20': 96,
 '2020-04-18': 72,
 '2020-04-17': 96,
 '2020-04-16': 63,
 '2020-04-15': 81,
 '2020-04-14': 95,
 '2020-04-10': 24,
 '2020-04-09': 104,
 '2020-04-08': 115,
 '2020-04-07': 184,
 '2020-04-06': 71,
 '2020-04-05': 44,
 '2020-04-03': 186,
 '2020-04-02': 72,
 '2020-03-31': 24,
 '2020-03-30': 66,
 '2020-03-28': 21,
 '2020-03-27': 182,
 '2020-03-26': 100,
 '2020-03-25': 129,
 '2020-03-24': 25,
 '2020-03-23': 192,
 '2020-03-22': 20,
 '2020-03-20': 121,
 '2020-03-19': 87,
 '2020-03-18': 203,
 '2020-03-17': 215,
 '2020-03-16': 80,
 '2020-03-14': 50,
 '2020-03-13': 215,
 '2020-03-12': 229,
 '2020-03-11': 285,
 '2020-03-10': 253,
 '2020-03-06': 224,
 '2020-03-05': 140,
 '2020-03-04': 144,
 '2020-03-03': 47,
 '2020-03-02': 185,
 '2020-02-28': 48,
 '2020-02-27': 207,
 '2020-02-26': 192,
 '2020-02-25': 318,
 '2020-02-22': 9,
 '2020-02-21': 213,
 '2020-02-20': 98,
 '2020-02-19': 319,
 '2020-02-18': 255,
 '2020-02-17': 320,
 '2020-02-14': 359,
 '2020-02-13': 109,
 '2020-02-12': 144,
 '2020-02-11': 95,
 '2020-02-10': 72,
 '2020-02-07': 12,
 '2020-02-06': 124,
 '2020-02-05': 149,
 '2020-02-04': 155,
 '2020-02-03': 207,
 '2020-02-01': 101,
 '2020-01-31': 39,
 '2020-01-30': 92,
 '2020-01-29': 349,
 '2020-01-28': 246,
 '2020-01-27': 123,
 '2020-01-23': 181,
 '2020-01-22': 108,
 '2020-01-21': 260,
 '2020-01-20': 54,
 '2020-01-17': 207,
 '2020-01-16': 112,
 '2020-01-15': 48,
 '2020-01-14': 120,
 '2020-01-10': 116,
 '2020-01-09': 48,
 '2020-01-08': 2,
 '2019-12-28': 14,
 '2019-12-27': 95,
 '2019-12-26': 243,
 '2019-12-25': 346,
 '2019-12-24': 96,
 '2019-12-23': 299,
 '2019-12-20': 285,
 '2019-12-19': 96,
 '2019-12-18': 168,
 '2019-12-17': 212,
 '2019-12-16': 98,
 '2019-12-13': 144,
 '2019-12-12': 75,
 '2019-12-11': 144,
 '2019-12-10': 72,
 '2019-12-09': 196,
 '2019-12-06': 120,
 '2019-12-05': 164,
 '2019-12-04': 139,
 '2019-12-03': 309,
 '2019-12-02': 172,
 '2019-11-29': 72,
 '2019-11-28': 67,
 '2019-11-27': 181,
 '2019-11-26': 49,
 '2019-11-25': 331,
 '2019-11-22': 141,
 '2019-11-21': 72,
 '2019-11-20': 117,
 '2019-11-19': 124,
 '2019-11-18': 64,
 '2019-11-15': 229,
 '2019-11-14': 216,
 '2019-11-13': 89,
 '2019-11-12': 187,
 '2019-11-11': 215,
 '2019-11-08': 96,
 '2019-11-07': 96,
 '2019-11-06': 27,
 '2019-11-05': 51,
 '2019-11-01': 48,
 '2019-10-31': 143,
 '2019-10-30': 163,
 '2019-10-29': 176,
 '2019-10-28': 132,
 '2019-10-25': 228,
 '2019-10-24': 48,
 '2019-10-23': 120,
 '2019-10-22': 48,
 '2019-10-21': 126,
 '2019-10-18': 127,
 '2019-10-17': 196,
 '2019-10-16': 129,
 '2019-10-15': 188,
 '2019-10-14': 144,
 '2019-10-13': 21,
 '2019-10-12': 28,
 '2019-10-11': 235,
 '2019-10-10': 72,
 '2019-10-09': 171,
 '2019-10-08': 12,
 '2019-10-07': 144,
 '2019-10-04': 219,
 '2019-10-03': 141,
 '2019-10-02': 318,
 '2019-10-01': 114,
 '2019-09-30': 192,
 '2019-09-27': 26,
 '2019-09-26': 244,
 '2019-09-25': 407,
 '2019-09-24': 428,
 '2019-09-23': 386,
 '2019-09-22': 24,
 '2019-09-20': 275,
 '2019-09-19': 96,
 '2019-09-18': 432,
 '2019-09-17': 534,
 '2019-09-16': 286,
 '2019-09-13': 174,
 '2019-09-12': 245,
 '2019-09-11': 487,
 '2019-09-10': 96,
 '2019-09-09': 124,
 '2019-09-06': 537,
 '2019-09-05': 437,
 '2019-09-04': 179,
 '2019-09-03': 250,
 '2019-09-02': 72,
 '2019-08-30': 72,
 '2019-08-29': 144,
 '2019-08-28': 338,
 '2019-08-27': 340,
 '2019-08-26': 114,
 '2019-08-23': 138,
 '2019-08-22': 225,
 '2019-08-21': 96,
 '2019-08-20': 169,
 '2019-08-19': 298,
 '2019-08-16': 1356,
 '2019-08-15': 72,
 '2019-08-14': 114,
 '2019-08-13': 96,
 '2019-08-12': 48,
 '2019-08-09': 103,
 '2019-08-08': 111,
 '2019-08-07': 69,
 '2019-08-06': 461,
 '2019-08-04': 8,
 '2019-08-02': 201,
 '2019-08-01': 147,
 '2019-07-31': 24,
 '2019-07-30': 120,
 '2019-07-29': 62,
 '2019-07-26': 96,
 '2019-07-25': 96,
 '2019-07-23': 260,
 '2019-07-22': 168,
 '2019-07-20': 24,
 '2019-07-19': 24,
 '2019-07-18': 228,
 '2019-07-17': 144,
 '2019-07-16': 48,
 '2019-07-15': 34,
 '2019-07-12': 101,
 '2019-07-10': 24,
 '2019-07-09': 24,
 '2019-07-08': 148,
 '2019-07-05': 65,
 '2019-07-04': 189,
 '2019-07-03': 213,
 '2019-07-02': 126,
 '2019-07-01': 133,
 '2019-06-29': 18,
 '2019-06-28': 136,
 '2019-06-27': 134,
 '2019-06-26': 97,
 '2019-06-25': 168,
 '2019-06-24': 32,
 '2019-06-21': 48,
 '2019-06-20': 48,
 '2019-06-19': 137,
 '2019-06-18': 125,
 '2019-06-17': 182,
 '2019-06-14': 24,
 '2019-06-13': 43,
 '2019-06-12': 76,
 '2019-06-11': 904,
 '2019-06-10': 162,
 '2019-06-08': 21,
 '2019-06-07': 207,
 '2019-06-06': 124,
 '2019-06-05': 321,
 '2019-06-04': 167,
 '2019-06-03': 28,
 '2019-06-02': 16,
 '2019-05-31': 69,
 '2019-05-30': 268,
 '2019-05-29': 161,
 '2019-05-28': 128,
 '2019-05-27': 70,
 '2019-05-24': 163,
 '2019-05-23': 103,
 '2019-05-22': 83,
 '2019-05-20': 249,
 '2019-05-17': 208,
 '2019-05-16': 258,
 '2019-05-15': 190,
 '2019-05-14': 72,
 '2019-05-13': 120,
 '2019-05-07': 93,
 '2019-05-06': 147,
 '2019-05-02': 48,
 '2019-04-30': 437,
 '2019-04-29': 128,
 '2019-04-27': 19,
 '2019-04-26': 69,
 '2019-04-24': 409,
 '2019-04-23': 112,
 '2019-04-22': 104,
 '2019-04-19': 24,
 '2019-04-18': 106,
 '2019-04-16': 72,
 '2019-04-15': 96,
 '2019-04-14': 2,
 '2019-04-13': 38,
 '2019-04-12': 88,
 '2019-04-11': 242,
 '2019-04-10': 24,
 '2019-04-09': 13,
 '2019-04-08': 72,
 '2019-04-05': 264,
 '2019-04-04': 257,
 '2019-04-03': 145,
 '2019-04-02': 24,
 '2019-04-01': 309,
 '2019-03-29': 26,
 '2019-03-27': 61,
 '2019-03-26': 96,
 '2019-03-25': 96,
 '2019-03-23': 9,
 '2019-03-22': 24,
 '2019-03-21': 96,
 '2019-03-20': 514,
 '2019-03-19': 280,
 '2019-03-18': 119,
 '2019-03-15': 278,
 '2019-03-14': 140,
 '2019-03-13': 143,
 '2019-03-12': 264,
 '2019-03-11': 244,
 '2019-03-07': 192,
 '2019-03-06': 20,
 '2019-03-05': 131,
 '2019-03-04': 205,
 '2019-03-01': 281,
 '2019-02-28': 216,
 '2019-02-27': 143,
 '2019-02-26': 113,
 '2019-02-25': 24,
 '2019-02-22': 48,
 '2019-02-21': 44,
 '2019-02-20': 48,
 '2019-02-19': 343,
 '2019-02-18': 181,
 '2019-02-15': 65,
 '2019-02-14': 93,
 '2019-02-13': 143,
 '2019-02-12': 72,
 '2019-02-08': 65,
 '2019-02-07': 127,
 '2019-02-06': 164,
 '2019-02-05': 264,
 '2019-02-04': 48,
 '2019-02-02': 23,
 '2019-01-31': 149,
 '2019-01-30': 30,
 '2019-01-29': 204,
 '2019-01-28': 78,
 '2019-01-25': 24,
 '2019-01-24': 4,
 '2019-01-23': 355,
 '2019-01-22': 96,
 '2019-01-21': 76,
 '2019-01-18': 427,
 '2019-01-17': 195,
 '2019-01-16': 148,
 '2019-01-15': 140,
 '2019-01-14': 151,
 '2019-01-11': 81,
 '2019-01-10': 136,
 '2019-01-09': 66,
 '2018-12-26': 21,
 '2018-12-25': 56,
 '2018-12-21': 101,
 '2018-12-20': 69,
 '2018-12-19': 182,
 '2018-12-18': 124,
 '2018-12-17': 170,
 '2018-12-14': 308,
 '2018-12-13': 291,
 '2018-12-12': 114,
 '2018-12-11': 117,
 '2018-12-10': 164,
 '2018-12-07': 448,
 '2018-12-06': 23,
 '2018-12-05': 137,
 '2018-12-04': 95,
 '2018-12-03': 132,
 '2018-12-01': 12,
 '2018-11-30': 176,
 '2018-11-29': 48,
 '2018-11-28': 58,
 '2018-11-27': 96,
 '2018-11-26': 76,
 '2018-11-23': 101,
 '2018-11-22': 283,
 '2018-11-21': 244,
 '2018-11-20': 148,
 '2018-11-19': 376,
 '2018-11-16': 72,
 '2018-11-15': 244,
 '2018-11-14': 74,
 '2018-11-13': 95,
 '2018-11-12': 317,
 '2018-11-09': 146,
 '2018-11-08': 24,
 '2018-11-07': 197,
 '2018-11-06': 168,
 '2018-11-02': 48,
 '2018-11-01': 220,
 '2018-10-31': 114,
 '2018-10-30': 86,
 '2018-10-29': 94,
 '2018-10-26': 72,
 '2018-10-25': 192,
 '2018-10-24': 371,
 '2018-10-23': 287,
 '2018-10-22': 229,
 '2018-10-19': 177,
 '2018-10-18': 182,
 '2018-10-17': 30,
 '2018-10-16': 105,
 '2018-10-15': 120,
 '2018-10-12': 245,
 '2018-10-10': 132,
 '2018-10-09': 91,
 '2018-10-08': 400,
 '2018-10-06': 2,
 '2018-10-05': 180,
 '2018-10-04': 108,
 '2018-10-03': 111,
 '2018-10-02': 209,
 '2018-10-01': 144,
 '2018-09-28': 168,
 '2018-09-27': 251,
 '2018-09-26': 859,
 '2018-09-25': 450,
 '2018-09-24': 96,
 '2018-09-21': 259,
 '2018-09-20': 187,
 '2018-09-19': 663,
 '2018-09-18': 751,
 '2018-09-17': 389,
 ...}

In [26]:
research = {}
for key, value in registrations.items():
    year, month, _ = key.split('-')
    if year not in research.keys():
        research[year] = {}
    if month not in research[year].keys():
        research[year][month] = 0
    research[year][month] += value

In [27]:
research

{'2022': {'05': 89, '04': 448, '03': 759, '02': 615, '01': 456},
 '2021': {'12': 1085,
  '11': 1391,
  '10': 1256,
  '09': 2724,
  '08': 1703,
  '07': 1957,
  '06': 1678,
  '05': 1962,
  '04': 2369,
  '03': 2607,
  '02': 2420,
  '01': 1832},
 '2020': {'12': 3310,
  '11': 3148,
  '10': 4034,
  '09': 7872,
  '08': 2803,
  '07': 3093,
  '06': 2959,
  '05': 2248,
  '04': 2321,
  '03': 3237,
  '02': 3506,
  '01': 2105},
 '2019': {'12': 3487,
  '11': 2472,
  '10': 3443,
  '09': 5931,
  '08': 4720,
  '07': 2351,
  '06': 3218,
  '05': 2430,
  '04': 3054,
  '03': 3219,
  '02': 2224,
  '01': 2360},
 '2018': {'12': 2564,
  '11': 3211,
  '10': 3681,
  '09': 7154,
  '08': 3039,
  '07': 1871,
  '06': 1407,
  '05': 1570,
  '04': 1897,
  '03': 2016,
  '02': 2146,
  '01': 1447},
 '2017': {'12': 2737,
  '11': 2061,
  '10': 4372,
  '09': 5453,
  '08': 3226,
  '07': 1789,
  '06': 2185,
  '05': 2023,
  '04': 1130,
  '03': 2149,
  '02': 1252,
  '01': 1959},
 '2016': {'12': 1658,
  '11': 2203,
  '10': 11388,
  '09': 7960,
  '08': 1028,
  '07': 975,
  '06': 1328,
  '05': 1613,
  '04': 1421,
  '03': 1772,
  '02': 2551,
  '01': 1450},
 '2015': {'12': 2714,
  '11': 2339,
  '10': 3714,
  '09': 3845,
  '08': 1667,
  '07': 1512,
  '06': 2404,
  '05': 1560,
  '04': 1690,
  '03': 999,
  '02': 1401,
  '01': 995},
 '2014': {'12': 1542,
  '11': 1052,
  '10': 2160,
  '09': 2220,
  '08': 1385,
  '07': 921,
  '06': 1128,
  '05': 1289,
  '04': 1311,
  '03': 1799,
  '02': 1592,
  '01': 1182},
 '2013': {'12': 1742,
  '11': 1412,
  '10': 1160,
  '09': 2391,
  '08': 1198,
  '07': 1732,
  '06': 1525,
  '05': 1131,
  '04': 1989,
  '03': 1856,
  '02': 2000,
  '01': 1504},
 '2012': {'12': 1353,
  '11': 2446,
  '10': 1949,
  '09': 2221,
  '08': 1276,
  '07': 1993,
  '06': 1575,
  '05': 1374,
  '04': 1289,
  '03': 1493,
  '02': 1554,
  '01': 759},
 '2011': {'12': 1312,
  '11': 1426,
  '10': 1168,
  '09': 2390,
  '08': 946,
  '07': 1195,
  '06': 1111,
  '05': 1056,
  '04': 1800,
  '03': 1547,
  '02': 1541,
  '01': 873},
 '2010': {'12': 1178,
  '11': 686,
  '10': 1323,
  '09': 1796,
  '08': 1503,
  '07': 894,
  '06': 1118,
  '05': 945,
  '04': 1439,
  '03': 973,
  '02': 647,
  '01': 863},
 '2009': {'12': 1566,
  '11': 845,
  '10': 1029,
  '09': 1313,
  '08': 947,
  '07': 971,
  '06': 812,
  '05': 1511,
  '04': 901,
  '03': 791,
  '02': 1072,
  '01': 1312},
 '2008': {'12': 587,
  '11': 1016,
  '10': 814,
  '09': 1616,
  '08': 1021,
  '07': 1067,
  '06': 1343,
  '05': 1302,
  '04': 1380,
  '03': 633,
  '02': 1443,
  '01': 470},
 '2007': {'12': 1004,
  '11': 817,
  '10': 738,
  '09': 462,
  '08': 728,
  '07': 529,
  '06': 520,
  '05': 707,
  '04': 459,
  '03': 480,
  '02': 515,
  '01': 397},
 '2006': {'12': 1177,
  '11': 549,
  '10': 287,
  '09': 858,
  '08': 1025,
  '07': 794,
  '06': 629,
  '05': 527,
  '04': 337,
  '03': 349,
  '02': 645,
  '01': 673},
 '2005': {'12': 463,
  '11': 288,
  '10': 692,
  '09': 286,
  '08': 474,
  '07': 511,
  '06': 78,
  '05': 272,
  '04': 104,
  '03': 270,
  '02': 96,
  '01': 133},
 '2004': {'12': 248,
  '11': 196,
  '10': 292,
  '09': 383,
  '08': 199,
  '07': 233,
  '06': 199,
  '05': 260,
  '04': 190,
  '03': 374,
  '02': 242,
  '01': 396},
 '2003': {'12': 335,
  '11': 136,
  '10': 284,
  '09': 329,
  '08': 251,
  '07': 691,
  '06': 232,
  '05': 240,
  '04': 256,
  '03': 282,
  '02': 42,
  '01': 2095},
 '2002': {'12': 286,
  '11': 128,
  '10': 315,
  '09': 136,
  '08': 196,
  '07': 463,
  '06': 48,
  '05': 17,
  '04': 112,
  '03': 246,
  '02': 96,
  '01': 475},
 '2001': {'12': 48,
  '11': 126,
  '10': 72,
  '09': 11,
  '08': 164,
  '06': 185,
  '05': 181,
  '04': 114,
  '02': 39,
  '01': 347},
 '2000': {'12': 89,
  '11': 17,
  '10': 124,
  '09': 48,
  '08': 72,
  '07': 24,
  '06': 62,
  '05': 96,
  '04': 24,
  '03': 140,
  '02': 66,
  '01': 11},
 '1999': {'07': 48, '01': 96},
 '1998': {'09': 4, '07': 12, '03': 24},
 '1997': {'02': 18, '01': 48},
 '1992': {'01': 24},
 '1900': {'01': 56}}

In [28]:
result_values = {}
for key in research.keys():
    for month in sorted(research[key]):
        if key not in result_values.keys():
            result_values[key] = []
        result_values[key].append(research[key][month])

In [18]:
result_values

{'2022': [456, 615, 759, 448, 89],
 '2021': [1832,
  2420,
  2607,
  2369,
  1962,
  1678,
  1957,
  1703,
  2724,
  1256,
  1391,
  1085],
 '2020': [2105,
  3506,
  3237,
  2321,
  2248,
  2959,
  3093,
  2803,
  7872,
  4034,
  3148,
  3310],
 '2019': [2360,
  2224,
  3219,
  3054,
  2430,
  3218,
  2351,
  4720,
  5931,
  3443,
  2472,
  3487],
 '2018': [1447,
  2146,
  2016,
  1897,
  1570,
  1407,
  1871,
  3039,
  7154,
  3681,
  3211,
  2564],
 '2017': [1959,
  1252,
  2149,
  1130,
  2023,
  2185,
  1789,
  3226,
  5453,
  4372,
  2061,
  2737],
 '2016': [1450,
  2551,
  1772,
  1421,
  1613,
  1328,
  975,
  1028,
  7960,
  11388,
  2203,
  1658],
 '2015': [995,
  1401,
  999,
  1690,
  1560,
  2404,
  1512,
  1667,
  3845,
  3714,
  2339,
  2714],
 '2014': [1182,
  1592,
  1799,
  1311,
  1289,
  1128,
  921,
  1385,
  2220,
  2160,
  1052,
  1542],
 '2013': [1504,
  2000,
  1856,
  1989,
  1131,
  1525,
  1732,
  1198,
  2391,
  1160,
  1412,
  1742],
 '2012': [759,
  1554,
  1493,
  1289,
  1374,
  1575,
  1993,
  1276,
  2221,
  1949,
  2446,
  1353],
 '2011': [873,
  1541,
  1547,
  1800,
  1056,
  1111,
  1195,
  946,
  2390,
  1168,
  1426,
  1312],
 '2010': [863, 647, 973, 1439, 945, 1118, 894, 1503, 1796, 1323, 686, 1178],
 '2009': [1312, 1072, 791, 901, 1511, 812, 971, 947, 1313, 1029, 845, 1566],
 '2008': [470, 1443, 633, 1380, 1302, 1343, 1067, 1021, 1616, 814, 1016, 587],
 '2007': [397, 515, 480, 459, 707, 520, 529, 728, 462, 738, 817, 1004],
 '2006': [673, 645, 349, 337, 527, 629, 794, 1025, 858, 287, 549, 1177],
 '2005': [133, 96, 270, 104, 272, 78, 511, 474, 286, 692, 288, 463],
 '2004': [396, 242, 374, 190, 260, 199, 233, 199, 383, 292, 196, 248],
 '2003': [2095, 42, 282, 256, 240, 232, 691, 251, 329, 284, 136, 335],
 '2002': [475, 96, 246, 112, 17, 48, 463, 196, 136, 315, 128, 286],
 '2001': [347, 39, 114, 181, 185, 164, 11, 72, 126, 48],
 '2000': [11, 66, 140, 24, 96, 62, 24, 72, 48, 124, 17, 89],
 '1999': [96, 48],
 '1998': [24, 12, 4],
 '1997': [48, 18],
 '1992': [24],
 '1900': [56]}

In [24]:
cities_filtered = {}
n_of_city = 0
for key, value in cities.items():
    if n_of_city < 5:
        cities_filtered[key] = value
        n_of_city += 1
    else:
        if 'Остальные' not in cities_filtered.keys():
            cities_filtered['Остальные'] = 0
        cities_filtered['Остальные'] += value

In [25]:
cities_filtered

{'Уфа': 59076,
 'Москва': 31072,
 'Краснодар': 21470,
 'Санкт-Петербург': 12982,
 'Стерлитамак': 12454,
 'Остальные': 233361}